code refactoring
rbredtech/consent-management-provider pull request #37
Opened 2022-12-12 15:13 UTC by ajantsch

2022-12-13 09:41 UTC, danielkocsan approved these changes

2022-12-20 11:55 UTC, Mgutjahr commented on src/templates/banner.js
> +    consentBanner.style.display = 'none';
no use before declaration

2022-12-20 14:40 UTC, danielkocsan requested changes

2022-12-20 14:40 UTC, danielkocsan commented on src/templates/cmp.js
> +          localStorage.setItem('<%-TECH_COOKIE_NAME%>', xt);
I think this will set an entry on the channel's hbbTv app domain, which we don't want.

2022-12-20 14:40 UTC, danielkocsan commented on src/templates/cmp.js
> +        if (
With this condition here it loads the iframe-less API every time. Which could be fine if you remove 
```const tcfapiJs = await renderFile(path.join(__dirname, "../templates/tcfapi.js"), values);```
from `tcfapiIframe.ts`.

2022-12-20 15:30 UTC, ajantsch commented on src/config/index.ts
> +  1000 * 60 * 60 * 24 * 365 * 2, // 2 years
Trailing commas setting is by default `es5`

"Default value changed from `none` to `es5` in v2.0.0"

2022-12-20 15:31 UTC, ajantsch commented on spec/debug-api.spec.disabled.js
> +const { describe, beforeAll, test, expect, afterAll } = require("@jest/globals");
If you have an idea on how to make it work again, I would love to re-enable it. Currently it happens that, if run alone, these tests pass, but if run with the other tests, then it fails.

2022-12-20 16:03 UTC, Mgutjahr commented on src/templates/banner.js
> +        KeyEvent.VK_ENTER = KeyEvent.VK_ENTER || window['VK_ENTER'] || 13;
Why is this `VK_ENTER` config setting here in the case block? This is a constant that does not depend on the call and should be extracted to the outer block (together with the other key configs)

2022-12-20 16:03 UTC, Mgutjahr commented on src/templates/banner.js
> +    case 'isBannerVisible':
this should be handled in the handleVK method

2022-12-20 16:04 UTC, Mgutjahr commented on src/templates/cmp.js
> +        if (!localStorage.getItem('<%-TECH_COOKIE_NAME%>')) {
why is xt? - please use readable variable name

2022-12-20 16:08 UTC, Mgutjahr commented on src/templates/cmp.js
> +      }
Would be great if we could extract this logic for getting the existing consent decision into a shared function .. as this is also needed in tcfapi.js

2022-12-20 16:09 UTC, Mgutjahr commented on src/templates/cmp.js
> +        return;
This should only be called if iFrame is not supported - otherwise it is attached twice

2022-12-20 16:10 UTC, Mgutjahr commented on src/templates/tcfapi.js
> +    case 'addEventListener':
can we remove this method?

2022-12-20 16:10 UTC, Mgutjahr commented on src/templates/tcfapi.js
> +    case 'removeEventListener':
can we remove this method?

2022-12-20 16:13 UTC, Mgutjahr commented on index.ejs
> +  <script type='text/javascript'
would be great if the exposed function would match the name of the included script, e.g. `__tcfapi` is provided thorugh `tcfapi.js`

2022-12-20 16:16 UTC, Mgutjahr reviewed
checkout my comments in the code

2022-12-23 12:21 UTC, Mgutjahr approved these changes

2022-12-23 12:27 UTC, merged